env: local
migrations_path: ./migrations

database:
  timeout: 5s
  attempts: 5
  delay: 5s

http_server:
  port: 8080
  timeout: 5s
  idle_timeout: 1m

library_server:
  protocol: http
  host: localhost
  port: 8090

